### ISSUE TITLE
与其他插件/主题（未知）一起使用时，倍数按钮错位

### ISSUE THREAD

**Issue by lgc2333** [BetterNCM/PlaybackRate#1]
![image](https://user-images.githubusercontent.com/59048777/230760328-76a4f347-afa6-4cca-9d6a-d638d77f72e4.png)

已安装插件列表
![image](https://user-images.githubusercontent.com/59048777/230760357-f43580b4-b1a9-45a4-845d-5fd56dfe14f6.png)

MikuPlugin 配置
![image](https://user-images.githubusercontent.com/59048777/230760372-7ee2f6e0-c9b9-4498-a6a4-db1a1e1c74e2.png)

**Comment by lgc2333** [comment]
0.1.1版本 跑这来了![image](https://user-images.githubusercontent.com/59048777/230761897-a4e1d2ce-1b14-4d05-a1fe-857591d7cbe7.png)

**Comment by Yu-xiaohei** [comment]
原来不止我出现这个问题了呀
23333
